### ISSUE TITLE
Publish list of cog/over contacts

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC-transition-site#117]
Per feedback from office hours, folks are having a hard time finding and understanding their cog/over assignments. There's also new [guidance from OMB](https://www.whitehouse.gov/wp-content/uploads/2024/04/M-24-11-Revisions-to-2-CFR.pdf).

- [ ] Publish the list of Cog/Over contacts on the FAC website ([Drive link](https://docs.google.com/spreadsheets/d/139hThIs_XHst4d6K-6m4PXm4UJ-OEgQK/edit?usp=drive_link&ouid=113323386353610336222&rtpof=true&sd=true))
- [ ] Update [compliance supplement page](https://www.fac.gov/compliance/) to describe where to find contacts 
- [ ] Update [search filter descriptions](https://www.fac.gov/search-resources/filters/) to explain what cog/over results mean and link to supplements page

**Comment by lauraherring** [comment]
@danswick @Leighdiddy  I'm actually just reading through the new OMB memo now and I think we might have gotten slightly ahead of ourselves with this ticket/want to discuss further because I don't think this list is quite as straight forward as we (or at least I) thought even earlier this afternoon.

**Comment by jadudm** [comment]
It would be good to discuss. I don't know that the two are linked? (Or, I'm curious to hear what the linkage is?)

That is, I believe we're required to provide a list of contacts for the cognitive agencies. We had a PDF that was linked in with this contact info broken out before the update, I thought.

https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200/subpart-F/subject-group-ECFRed80de82be1f4a3/section-200.513

**Comment by danswick** [comment]
Based on discussion with OMB, I think we do want to pursue this ticket or something similar.

**Comment by Leighdiddy** [comment]
Leaving for future convo: Is the work detailed in this ticket covered here? https://github.com/GSA-TTS/FAC/issues/4231
