### ISSUE TITLE
[FAC threshold] Update submission guide (copy and screenshots), FAQs, and possibly other static sites

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC-transition-site#165]
Update submission guide (copy and screenshots), FAQs, and possibly other static sites with new threshold info.

**Comment by analynd** [comment]
Just documenting here: I'm going through the [Submission Guide page on James M's branch](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/JM-submission-guide-threshold-change-2024/audit-resources/how-to/) and referencing the [app on the test site](https://fac-preview.app.cloud.gov/) for the screenshots.

**Comment by James-Paul-Mason** [comment]
Complete!
